### PR TITLE
36 - Service broker correctly handles empty `CONJUR_SSL_CERTIFICATE` env var

### LINKED ISSUE #36: Empty CONJUR_SSL_CERTIFICATE environment variable causes error
If the service broker is turned on with an empty `CONJUR_SSL_CERTIFICATE` environment variable, the health check will fail with the error `OpenSSL::X509::CertificateError: header too long` because the empty string `ConjurClient.ssl_cert` is evaluating to `true` in `lib/conjur_client.rb`.

The service broker needs to be updated to handle when the `CONJUR_SSL_CERTIFICATE` env var is present but empty.

### PR DESCRIPTION
**Pull request by izgeri**
Closes #36 

This update addresses an issue where the SB was attempting to parse an empty `CONJUR_SSL_CERTIFICATE` env var.

### CODE REVIEW

File: lib/conjur_client.rb [hunk 1]
```diff
@@ -28,7 +28,7 @@ def policy
     end
   
     def ssl_cert
-      ENV['CONJUR_SSL_CERTIFICATE']
+      ENV['CONJUR_SSL_CERTIFICATE'] unless ENV['CONJUR_SSL_CERTIFICATE'].to_s.empty?
```
Comment (kgilpin) [inline lib/conjur_client.rb]: Because you have active_support, you can say `unless ENV['CONJUR_SSL_CERTIFICATE'].blank?`

Comment (izgeri) [reply lib/conjur_client.rb]: Ah, I thought we removed it and I forgot to check. Thanks for the efficient Ruby! :)

**Comment by jtuttle** [comment]
LGTM
